### ISSUE TITLE
Feature: User can create an album

### ISSUE THREAD

**Issue by heerakmoon** [heerakmoon/Final-Project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an album

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the plus button next to 'New Album'. From there they choose what their album name with be and put it in the 'Name' input and add a description to the album if they wish. Then they click the 'create album' button to create the album. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/113075380/233163960-1d41f83b-007e-4486-b760-71c3f35ff9d2.png)
![image](https://user-images.githubusercontent.com/113075380/233164390-7ff6e827-73db-4ee1-9756-0a47c9990e2b.png)
![image](https://user-images.githubusercontent.com/113075380/233164510-f72315a2-157f-4d59-9460-d4ff5023658e.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update new album information to the album table

### ☁️ Server Tasks

- [x] Send a POST request when user adds text to the 'Name' and 'Description' input and creates the album
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x]  Display a message if there are no albums
- [x]  Create an 'add' button component that can be reused for both 'add album' and 'add photos'
- [x]  Create another button component that can be used for 'create album' and 'delete selected'
- [x]  Create a nav bar component
- [x]  Create a form component that takes the name of the album and an optional description
- [x]  Create a component that displays the existing album(s)

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
